
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    ca_org3:
        networks:
            skcript:
                aliases:
                    - ca_org3
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == org.entity.2
        image: hyperledger/fabric-ca:x86_64-1.1.0
        hostname: ca.org3.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org3
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/61c201af2b69df5fe8c4876f3f0388bed3a41e77d095f854f629fc92988768f6_sk
        ports:
            - 11054:7054   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == org.entity.2
        image: hyperledger/fabric-couchdb:x86_64-0.4.6
        hostname: couchdb0_org3
        networks:
           - skcript

    couchdb1_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == org.entity.2
        image: hyperledger/fabric-couchdb:x86_64-0.4.6
        hostname: couchdb1_org3
        networks:
           - skcript
